apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source-code
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git@github.com:majinghe/Demo.git

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: devops-code
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: git@github.com:majinghe/GitOps-demo.git

---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image
spec:
  type: image
  params:
    - name: url
      value: dllhb/gotc-gitops
